create table BOOKS
(
     BOOK_ID INTEGER PRIMARY KEY,
     NAME VARCHAR(30) NOT NULL,
     abbreviation VARCHAR(10) NOT NULL
);

create table VERSES (
      BOOK_ID INTEGER NOT NULL REFERENCES BOOKS(BOOK_ID) on delete cascade,
      CHAPTER smallint NOT NULL,
      VERSE smallint NOT NULL,
      PRIMARY KEY (BOOK_ID, CHAPTER, VERSE)
);

CREATE TABLE VERSE_TRANSLATIONS
(
     VERSE_TRANSLATION_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
     LANGUAGE VARCHAR(5) NOT NULL,
     NAME VARCHAR(50) NOT NULL,
     CONTENT TEXT NOT NULL,
     BOOK_ID   INT NOT NULL,
     CHAPTER   INT NOT NULL,
     VERSE     INT NOT NULL,
     CONSTRAINT FK_VERSE_TRANSLATIONS_VERSES
         FOREIGN KEY (BOOK_ID, CHAPTER, VERSE) REFERENCES VERSES(BOOK_ID, CHAPTER, VERSE) ON DELETE CASCADE,
     UNIQUE (LANGUAGE, BOOK_ID, CHAPTER, VERSE)
);

create table VERSE_POST (
      VERSE_POST_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      SLUG VARCHAR(400) NOT NULL UNIQUE,
      CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

create table VERSE_POST_TRANSLATIONS (
      VERSE_POST_TRANSLATION_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      VERSE_POST_ID UUID NOT NULL,
      LANGUAGE VARCHAR(5) NOT NULL,
      content TEXT NOT NULL,
      image_url TEXT NOT NULL,
      CONSTRAINT FK_VERSE_POST_TRANSLATIONS_VERSE_POST
         FOREIGN KEY (VERSE_POST_ID) REFERENCES VERSE_POST(VERSE_POST_ID) ON DELETE CASCADE
);

CREATE TABLE NOTICED_VERSES (
          BOOK_ID   INT NOT NULL,
          CHAPTER   INT NOT NULL,
          VERSE     INT NOT NULL,
          verse_post_id UUID,
          PRIMARY KEY (BOOK_ID, CHAPTER, VERSE),
          CONSTRAINT fk_NOTICED_VERSES_verse
              FOREIGN KEY (BOOK_ID, CHAPTER, VERSE) REFERENCES VERSES(BOOK_ID, CHAPTER, VERSE) ON DELETE CASCADE,
          CONSTRAINT fk_NOTICED_VERSES_post
              FOREIGN KEY (verse_post_id) REFERENCES verse_post(verse_post_id) ON DELETE SET NULL
);