ALTER TABLE VERSE_POST
    ADD COLUMN BOOK_ID INTEGER not null;
ALTER TABLE VERSE_POST
    ADD COLUMN CHAPTER INTEGER not null;
ALTER TABLE VERSE_POST
    ADD COLUMN VERSE INTEGER not null;

ALTER TABLE VERSE_POST
    ADD CONSTRAINT fk_VERSE_POST_TO_VERSE
        FOREIGN KEY (BOOK_ID, CHAPTER, VERSE)
            REFERENCES VERSES (BOOK_ID, CHAPTER, VERSE);

